#include "Cercle.h"
#include "FormesGeometriques.h"
#include <cmath>
#include <iostream>




double Cercle::CalculerSurface(double diametre, double inutile)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 begin
{
    double rayon = diametre / 2;
    Surface = PI * pow(rayon,2);
    return Surface;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre, double inutile)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A begin
{
    Perimetre = PI * diametre;
    return Perimetre;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
Cercle::Cercle()
{
    std::cout << "Constructeur Cercle" << std::endl;
}