#include "Utilisateur.h"
#include "FormesGeometriques.h"
#include "TriangleRectangle.h"
#include "Rectangle.h"
#include "Cercle.h"
#include <iostream>



void Utilisateur::AfficherResultats()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 begin
{
    if (m_CodeFormeChoisie == 0)
    {
        std::cout << "Pour un TriangleRectangle base = " << m_x1 << " hauteur =  " << m_x2 << " surface = " << myFormesGeometriques->GetSurface() << " Perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
    }
    if (m_CodeFormeChoisie == 1)
    {
        std::cout << "Pour un Rectangle largeur = " << m_x1 << " hauteur = " << m_x2 << " surface =  " << myFormesGeometriques->GetSurface() << " Perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
    }
    if (m_CodeFormeChoisie == 2)
    {
        std::cout << "Pour un Cercle diametre = " << m_x1 << " surface = " << myFormesGeometriques->GetSurface() << " Perimetre = " << myFormesGeometriques->GetPerimetre() << std::endl;
    }
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Utilisateur::ChoisirForme(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 begin
{
    //std::cin >> m_CodeFormeChoisie;
    m_CodeFormeChoisie = CodeForme;
        if (m_CodeFormeChoisie == 0)
        {
             myFormesGeometriques = new TriangleRectangle();
        }
        if (m_CodeFormeChoisie == 1)
        {
            myFormesGeometriques = new Rectangle();
        }
        if (m_CodeFormeChoisie == 2)
        {
            myFormesGeometriques = new Cercle();
        }
    return 0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::SaisirLesParametres()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 begin
{
    if (m_CodeFormeChoisie == 0)
    {
        std::cout << "Entrez la base du Triangle rectangle" << std::endl;
        std::cin >> m_x1;
        std::cout << "Entrez la hauteur du Triangle rectangle" << std::endl;
        std::cin >> m_x2;
    }
    if (m_CodeFormeChoisie == 1)
    {
        std::cout << "Entrez la largeur du Rectangle" << std::endl;
        std::cin >> m_x1;
        std::cout << "Entrez la hauteur du Rectangle" << std::endl;
        std::cin >> m_x2;
    }
    if (m_CodeFormeChoisie == 2)
    {
        std::cout << "Entrez le diametre du Cercle" << std::endl;
        std::cin >> m_x1;
        m_x2 = 0;
    }
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::ExecuterLesCalculs()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 begin
{
    myFormesGeometriques->CalculerSurface(m_x1, m_x2);
    myFormesGeometriques->CalculerPerimetre(m_x1, m_x2);
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
